# Site
title:              Death and the Dancer
bio:                'Come dance away your worldly cares. When Death scrapes his bow, you’ll have no choice.'
description:        "Come dance away your worldly cares."
locale:             en_GB
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
source:             src
destination:        dist
sass:
    sass_dir:       ./assets/styles

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            deathanddancer
facebook:           deathandthedancer
instagram:          deathandthedancer
# github:             default
youtube:            UCi5v7BXSfKSqw8L65Y9xzfw

# personal
location:           Sheffield, UK
phone:              079565127647
email:              deathandthedancer@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
